// <auto-generated />
namespace ESRGC.Broadband.ETL.CensusBlock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TicketTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201305201829018_TicketTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
