// <auto-generated />
namespace ESRGC.Broadband.ETL.CensusBlock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class submittingUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(submittingUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201305171901140_submittingUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
